### ISSUE TITLE
vcs export fails to add nesting path prefix to nested repos

### ISSUE THREAD

**Issue by calvertdw** [dirk-thomas/vcstool#101]
Starting with an existing nested repository structure in `~/dev`:
```
repository-group
├── .git
├── nested-repo-one
│   └── .git
└── nested-repo-two
    └── .git
```
and running
```
~/dev $ vcs export --nested repository-group
```
the result is
```
repositories:
  repository-group:
    type: git
    url: https://<url>.git
    version: master
  nested-repo-one:
    type: git
    url: https://<url>.git
    version: develop
  nested-repo-two:
    type: git
    url: https://<url>.git
    version: develop
```
but should be 
```
repositories:
  repository-group:
    type: git
    url: https://<url>.git
    version: master
  repository-group/nested-repo-one:
    type: git
    url: https://<url>.git
    version: develop
  repository-group/nested-repo-two:
    type: git
    url: https://<url>.git
    version: develop
```

I had forgotten about the `export` command for a while. @dirk-thomas thanks for reminding me. Since we use nested repos in the IHMC build framework, this breaks that convenience for me. I'm guessing it's an easy fix. :smile:
