### ISSUE TITLE
vcs export --exact reports tag names instead of commit hash

### ISSUE THREAD

**Issue by crdelsey** [dirk-thomas/vcstool#109]
**Version:** vcs 0.2.4

**How to Reproduce:**
Run `vcs export --exact` on a set of repos.

**Expected behavior:**
The version field of each repo will report the exact commit hash like this:
```
  src/ros2/rclpy:
    type: git
    url: https://github.com/ros2/rclpy.git
    version: 76d26a125da7f9df19ba35beb60cb16838019a10
```

**Actual Behavior:**
Frequently the hash is replaced by a tag name.
```
  src/ros2/rcl_interfaces:
    type: git
    url: https://github.com/ros2/rcl_interfaces.git
    version: 0.8.0
```

---

I think when the --exact parameter is specified, it is preferable to provide the commit hash.
