### ISSUE TITLE
Importing non-local branches with older git version

### ISSUE THREAD

**Issue by avishefi** [dirk-thomas/vcstool#164]
Running `vcs import`, when a repository specified by a `vcs.yml` already exists, and specifying a branch name in the `version` field results in the following error (assuming the attempted branch checkout is named `test`):

`fatal: invalid reference: test`

This happens when the branch was not previously checked-out locally. The command that is executed by `vcstool/clients/git.py` is: `git checkout test --` which fails also when executed manually. However, executing the following command succeeds: `git checkout test`.

The import command should support checking out remote branches if not available locally so that switching between branches does not fail with the error mentioned.

**Comment by dirk-thomas** [comment]
Can you please add steps to reproduce this case, e.g. to setup the state of the local working copy before the `vcs import` call.

**Comment by avishefi** [comment]
Take a repository with two branches, for example, `master` and `test`.

Using the following vcs.yml file:
```yaml
repositories:
  test:
    type: git
    url: <repo-url>
    version: master
```

Execute: `vcs import < vcs.yml`

Once finished, modify the file `vcs.yml` and change the `version` field value to `test` so vcs.yml looks like the following:

```yaml
repositories:
  test:
    type: git
    url: <repo-url>
    version: test
```

Execute: `vcs import < vcs.yml`

Result:

```shell
=== ./test (git) ===
Could not checkout ref 'test': fatal: invalid reference: test
```

**Comment by dirk-thomas** [comment]
I tried exactly that with the below yaml files and the second `import` invocation switches the branch just fine:

```
Switched to a new branch 'kinetic-devel'
Branch 'kinetic-devel' set up to track remote branch 'kinetic-devel' from 'origin'.
```

First `yaml` file:
```
repositories:
  catkin:
    type: git
    url: https://github.com/ros/catkin.git
    version: noetic-devel
```

Second `yaml` file with a different branch:
```
repositories:
  catkin:
    type: git
    url: https://github.com/ros/catkin.git
    version: kinetic-devel
```

Please share more information about your environment: what platform, the version number of `vcstool`, `git`, Python, etc.
