### ISSUE TITLE
import doesn't pull, pull fails when version is a hash

### ISSUE THREAD

**Issue by tylerjw** [dirk-thomas/vcstool#165]
industrial_ci is using vcstool to import from .repos or .rosinstall files into a workspace.  Because we are also re-using docker images from previous runs we have the issue where the code in the workspace is out of date.  The easy solution to that is to have vcs tool call pull after import.  This presents a problem if the version was specified with a hash.  If this was done we get a failure like this:

```
=== /root/upstream_ws/src/ur/universal_robots_ros_driver (git) ===
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
```

```
- git:
    local-name: ur/universal_robots_ros_driver
    uri: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver
    version: 72453e14bfc262ade27c31d2086efc37a26543c6
```

I know that it is just running pull recursively.  I'd like some way to skip pulling if the version was set explicitly like this.  A way to do this with a custom git command would work too.
