### ISSUE TITLE
vcs is imprecise about git ref types

### ISSUE THREAD

**Issue by rotu** [dirk-thomas/vcstool#170]
vcs tries to be "smart" about git ref types in a way that is error-prone and limiting.

1. `version` can specify a branch, tag, or hash. But if this is not unique, but vcs provides no way to disambiguate, instead throwing an error when a branch and tag have the same name.
```
vcs import src < repos.yml
=== src/test-repo (git) ===
The version ref is a branch as well as tag but with different hashes
```
and warning when `version` could be either a tag or a hash
```
vcs import src < repos.yml
=== src/test-repo (git) ===
Cloning into '.'...
warning: refname '0246' is ambiguous.
Note: switching to '0246'.
...
```

2. If `version` is neither a branch nor a tag, `vcs` assumes it is a hash, leading to confusing error messages:
```
echo 'repositories: {vcstool: {type: git, url: "https://github.com/dirk-thomas/vcstool.git", version: tags/0.0.0}}' | vcs import src
=== src/vcstool (git) ===
Could not checkout ref 'tags/0.0.0': fatal: invalid reference: tags/0.0.0
```

3. There is not a way to tell vcstool to use a particular ref that is not a hash, branch, or tag:

```
echo 'repositories: {vcstool: {type: git, url: "https://github.com/dirk-thomas/vcstool.git", version: pull/100/head}}' | vcs import
=== ./vcstool (git) ===
Could not checkout ref 'pull/100/head': fatal: invalid reference: pull/100/head
```

vcs should have a way to specify an upstream ref explicitly and flexibly.

**Comment by dirk-thomas** [comment]
> vcs is sloppy about git ref types
> vcs tries to be "smart" about git ref types in a way that is error-prone and limiting.

If you don't want to alienate readers which you would like to help you on your issues it might be helpful to use better language than words like "sloppy".

> It would be nice to just put in the qualified ref (e.g. `heads/1.0.0` vs `tags/1.0.0`). It also doesn't allow refs that are neither a branch nor a tag, e.g. `refs/pull/123/merge`.

Can you please be more specific where you think this more specific refs should be used.

**Comment by rotu** [comment]
> If you don't want to alienate readers which you would like to help you on your issues it might be helpful to use better language than words like "sloppy".

Fixed. I was trying to not state the issue too narrowly. Basically the "version" is wishy-washy. It's simultaneously not specific enough to tell a tag from a branch with similar name and not general enough to point to a pull request `merge` ref.

> Can you please be more specific where you think this more specific refs should be used.

That's an implementation decision of a fix, but here's a few possibilities:

1. Version could contain a ref path that, if found, is used: e.g. `version: heads/1.0.0` versus `version: tags/1.0.0` versus `version: 1.0.0`. 
```
$ echo 'repositories: {vcstool: {type: git, url: "https://github.com/dirk-thomas/vcstool.git", version: tags/0.0.0}}' | vcs import src
=== src/vcstool (git) ===
Could not checkout ref 'tags/0.0.0': fatal: invalid reference: tags/0.0.0
```

This is probably the gentlest way forward and the above error confused me for a time (since `tags/0.0.0` is, in fact, a valid reference). I think 

2. An alternate key like `hash`/`branch`/`tag` could be admitted as an alternative to version, or a supplementary key like "`versiontype`":
```
repositories:
  vcstool:
    type: git
    url: https://github.com/dirk-thomas/vcstool.git
    tag: 0.0.0
  vcstool:
    type: git
    url: https://github.com/dirk-thomas/vcstool.git
    branch: master
```

3. An optional key "versiontype" could disambiguate the ref:

```
repositories:
  vcstool:
    type: git
    url: https://github.com/dirk-thomas/vcstool.git
    version: 0.0.0
    versiontype: tag
  vcstool:
    type: git
    url: https://github.com/dirk-thomas/vcstool.git
    version: master
    versiontype: branch
  vcstool:
    type: git
    url: https://github.com/dirk-thomas/vcstool.git
    version: pull/123/merge
    versiontype: ref
```
