### ISSUE TITLE
Unable to pull whl files

### ISSUE THREAD

**Issue by mikepurvis** [dirk-thomas/vcstool#201]
With this config:

```
repositories:
  requests:
    type: zip
    url: https://files.pythonhosted.org/packages/py2.py3/r/requests/requests-2.25.1-py2.py3-none-any.whl
    version: 2.25.1
```

I expected `vcs` to unpack the zipball, and it even claims to, but the resulting directory is empty (adding the `--debug` flag offers no further insight):

```
$ vcs import ws --input repos.yaml
=== ws/requests (zip) ===
Downloaded zipfile from 'https://files.pythonhosted.org/packages/py2.py3/r/requests/requests-2.25.1-py2.py3-none-any.whl' and unpacked it

$ find ws
ws
ws/requests
```

And as a small enhancement proposal, it would be an ergonomic improvement for this kind of use case if we could template the version number similar to how rosdistro yaml works:

```
repositories:
  requests:
    type: zip
    url: https://files.pythonhosted.org/packages/py2.py3/r/requests/requests-{version}-py2.py3-none-any.whl
    version: 2.25.1
```

**Comment by mikepurvis** [comment]
Oh wait, I read the source and it looks like it tries to do some clever stuff if you supply the `version` attribute; excluding it avoids this cleverness and gives the expected result:

```
repositories:
  requests:
    type: zip
    url: https://files.pythonhosted.org/packages/py2.py3/r/requests/requests-2.25.1-py2.py3-none-any.whl
```

https://github.com/dirk-thomas/vcstool/blob/2e90383a09e810049ee505e1e618690957c631dc/vcstool/clients/zip.py#L83-L101

Looks like `version` is being overloaded to mean "subdirectory within archive"? I wonder if it might be clearer to define a separate field for this selective-extraction behaviour— particularly since it's easy to imagine a scenario where one might prefer a _list_ of paths to extract (eg selective packages from monorepos like ros_controllers?
