### ISSUE TITLE
[feature] option to use hash attached to the relative path instead of the version field

### ISSUE THREAD

**Issue by andry81** [dirk-thomas/vcstool#251]
Git already does store submodule commit hash in a commit.

Example: https://github.com/andry81-tests/gil-test1-A/commit/f5f753fed28282a7297428e2eb158f948f719711

Which means if the yaml file has the `version` field then, it actually by default overrides a submodule branch commit to be checkouted:

```yaml
repositories:

  _externals/lib1:
    type:         git
    url:          https://github.com/user/lib1
    version:      master
```

The `_externals/lib1` is already committed here with the external repo hash (the url is not known internally).

I suggest to add an option to `import` command to use versions recorded for all submodules:

```cmd
>vcs import --use-internal-version < .externals
```

This will checkout versions has been committed the last time, not the versions declared in the `.externals` yaml file.
