### ISSUE TITLE
[feature] self checkout from a branch

### ISSUE THREAD

**Issue by andry81** [dirk-thomas/vcstool#252]
Sometimes need to checkout a branch that is already downloaded into the repository because that branch is a child directory to another repository branch:

```yaml
repositories:

  _externals/3_14_x:
    type:         git
    url:          .
    version:      3_14_x

  _externals/3_15_x:
    type:         git
    url:          .
    version:      3_15_x
```

, where the `3_x` is a parent (master) branch containing that `.externals` file.

Because `3_14_x` and `3_15_x` already downloaded, then I don't want to download them again and want to use current repository in the url: `.`

Or, for example, I could fetch only `3_14_x` and don't want to fetch `3_15_x` because each branch could weight hundreds of megabytes and I don't want to fetch them all in `vcs import ...`.

Or may be more advanced syntax:

```yaml
repositories:

  _externals/3_14_x:
    type:             git
    url:              <path-to-remote-repo-1>
    version:          3_14_x
    fetch-to-branch:  3_14_x

  _externals/3_15_x:
    type:             git
    url:              <path-to-remote-repo-1>
    version:          3_15_x
    fetch-to-branch:  3_15_x
```

, where `fetch-to-branch` will override default fetch and will checkout from the local branch.

Additionally add command line options with wildcards:

To exclude:

```cmd
>vcs import --skip-fetch-branches "3_14_*|3_15_*" < .externals
```

To exclusive include:

```cmd
>vcs import --checkout-branches "3_15_*|3_16_*" < .externals
```

Mixed (to rely on external fetch):

```cmd
>vcs import --skip-fetch-branches '*' --checkout-branches "3_15_*|3_16_*" < .externals
```

Is there a chance to add this?
