### ISSUE TITLE
Could not checkout ref '...': fatal: invalid reference

### ISSUE THREAD

**Issue by andry81** [dirk-thomas/vcstool#253]
Sometimes `could not checkout ref` error happens.

Steps to reproduce:

1. Create a repo with `1_2_3_20201010` branch (ex: https://github.com/andry81-tests/vcstool-test-A)
2. Switch to master branch:
    ```cmd
    git switch --orphan master
    ```
3. Create `.externals`:
    ```yaml
    repositories:

      _externals/1_2_3_20201010:
        type:             git
        url:              https://github.com/andry81-tests/vcstool-test-A
        version:          1_2_3_20201010
    ```
4. Import `.externals`:
    ```cmd
    vcs import < .externals
    ```
    > === .\_externals/1_2_3_20201010 (git) ===
    > Could not checkout ref '12320201010': fatal: invalid reference: 12320201010

```cmd
>git --version
git version 2.24.0.windows.2
```

**Comment by andry81** [comment]
Seems bug in the yaml parser, because this works:

```yaml
repositories:

  _externals/1_2_3_20201010:
    type:             git
    url:              https://github.com/andry81-tests/vcstool-test-A
    version:          '1_2_3_20201010'
```
