### ISSUE TITLE
bad non-descriptive error message 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by alecGraves** [dirk-thomas/vcstool#255]
This error message should be improved so it doesn't scare people, perhaps by describing exactly what data is set to None and maybe the line number of the input file.

Here is an example of a malformatted .repo file:
```yaml
# example.repo
repositories:
  bad:
  ament_cmake:
    type: git
    url: https://github.com/ament/ament_cmake.git
    version: humble
```
And here is the resulting output of vcs:
```
$ vcs import --input example.repos src
Input data is not valid format: 'NoneType' object is not subscriptable
```
