### ISSUE TITLE
Input data is not valid yaml format: mapping values are not allowed here

### ISSUE THREAD

**Issue by bhomaidan1990** [dirk-thomas/vcstool#259]
I'm using Ubuntu `20.04`, vcstools-0.1.42 installed via `pip`

I try to install my repositories like this:
`vcs import src --input link/pkgs.repos`

## pkgs.repos
```yaml
repositories:
  qpOASES:
    type: git
    url: https://github.com/kuka-isir/qpOASES.git
    version: master
  kdl-trajectories:
    type: git
    url: https://gitlab.inria.fr/auctus-team/components/control/kdl-trajectories.git
    version: master
```
I get an error:
```
Input data is not valid yaml format: mapping values are not allowed here
  in "<file>", line 3, column 17
```
Can you please tell me what can I do? thanks in advance.
