### ISSUE TITLE
[Feature Request] version by author or commit date-time

### ISSUE THREAD

**Issue by andry81** [dirk-thomas/vcstool#260]
For example, a dependency repository can be rewritten and lose the connection by the commit hash. But basically the commit author date stays intact.

To avoid dependency breakage is useful to add a date-time version:

```yaml
repositories:

  _externals/lib1:
    type:         git
    url:          https://github.com/user/lib1
    version:      {2023-03-17T13:21:23.320813Z}
```

Or more detailed:

```yaml
repositories:

  _externals/lib1:
    type:         git
    url:          https://github.com/user/lib1
    version:      {author@2023-03-17T13:21:23.320813Z}
```

This additionally can help to fix this issue: https://github.com/dirk-thomas/vcstool/issues/243
