### ISSUE TITLE
import fails to unpack some tar archives

### ISSUE THREAD

**Issue by apirek** [dirk-thomas/vcstool#279]
`import` does not unpack tar archives where the archive's root dir not match vcstool's expected pattern.
The archives are downloaded, no members of the archive are extracted, and success is reported.
Observed with the packages ignition_cmake2_vendor and ignition_math6_vendor.

How to reproduce:
```
mkdir src
vcs import src <<EOF
- tar:
    local-name: ignition_cmake2_vendor
    uri: https://github.com/ros2-gbp/ignition_cmake2_vendor-release/archive/release/humble/ignition_cmake2_vendor/0.0.2-2.tar.gz
    version: ignition_cmake2_vendor-release-release-humble-ignition_cmake2_vendor-0.0.2-2
- tar:
    local-name: ignition_math6_vendor
    uri: https://github.com/ros2-gbp/ignition_math6_vendor-release/archive/release/humble/ignition_math6_vendor/0.0.2-2.tar.gz
    version: ignition_math6_vendor-release-release-humble-ignition_math6_vendor-0.0.2-2
EOF
# Observe empty src/ignition_cmake2_vendor and src/ignition_math6_vendor.
```

The directory in ignition_cmake2_vendor's archive is
```
gz_cmake2_vendor-release-release-humble-ignition_cmake2_vendor-0.0.2-2
```
but vcstool expects 
```
ignition_cmake2_vendor-release-release-humble-ignition_cmake2_vendor-0.0.2-2
```
.

The directory in ignition_cmake2_vendor's archive is 
```
gz_math6_vendor-release-release-humble-ignition_math6_vendor-0.0.2-2
```
but vcstool expects
```
ignition_math6_vendor-release-release-humble-ignition_math6_vendor-0.0.2-2
```
.
