### ISSUE TITLE
tar with version leads to empty directory

### ISSUE THREAD

**Issue by VictorLamoine** [dirk-thomas/vcstool#287]
```
repositories:
  doxygen:
    type: tar
    url: https://github.com/doxygen/doxygen/releases/download/Release_1_13_2/doxygen-1.13.2.linux.bin.tar.gz
```

This works as expected:
```bash
vcs import --input repos.list

 ls -1 doxygen/
doxygen-1.13.2
```

But adding a version makes vcs fail:
```
repositories:
  doxygen:
    type: tar
    url: https://github.com/doxygen/doxygen/releases/download/Release_1_13_2/doxygen-1.13.2.linux.bin.tar.gz
    version: 1.13.2
```

```bash
vcs import --input repos.list

 ls -al doxygen/
```

The directory is empty

Am I using it wrong or is it a bug in the "members remapping"? 

https://github.com/dirk-thomas/vcstool/blob/daf389377310f7f31b2171f51a79af82c31bf3e2/vcstool/clients/tar.py#L71-L82
