### ISSUE TITLE
nested folders don't work

### ISSUE THREAD

**Issue by BrannonKing** [dirk-thomas/vcstool#40]
I get the error below even with the `--force` option:
```
=== src/localization (hg) ===
Could not clone repository 'https://mercurial.asirobots.com:8443/scm/hg/localization': abort: destination '.' is not empty
```

It seems a little weird that it creates the "localization" folder prematurely. From my repos file:
```
  localization:
    type: hg
    url: https://mercurial.asirobots.com:8443/scm/hg/localization
    version: default
  localization/src/AutoGenFusor:
    type: tar
    url: https://builder.domain.local/guestAuth/repository/download/MatlabScripts_FusorCodeGen/1.5.5c5faf48e415.91/builderOutput.tgz
    version: 1.5.5c5faf48e415.91
  localization/src/AutoGenMatchMaker:
    type: tar
    url: https://builder.domain.local/guestAuth/repository/download/MatlabScripts_PFCodeGen/1.8.e8c4885e9249.103/builderOutput.tgz
    version: 1.8.e8c4885e9249.103
```
