### ISSUE TITLE
support nested repos in all verbs

### ISSUE THREAD

**Issue by ihmc-rosie** [dirk-thomas/vcstool#57]
We use a git repo that configures a set of repositories within it. This works by gitignoring everything except a few key config files. However, vcstool does not automatically pick up these repositories.

**Comment by calvertdw** [comment]
This was supposed to be under my username. Was accidentally logged in as ihmc-rosie.

**Comment by dirk-thomas** [comment]
> We use a git repo that configures a set of repositories within it. This works by gitignoring everything except a few key config files.

Can you please clarify what exactly you mean with this and how you clone them "manually". Are you using git submodules?

**Comment by calvertdw** [comment]
Not using Git submodules. We allow our users to clone any repositories they want into a certain directory. We have build scripts that try to glue all those together into a single build. We version control those scripts. In our case it is Gradle build files. So via the gitignore, we have repos within a repo. Works totally fine with EGit, IntelliJ, and SmartGit. Would be nice if vcstool also handled that case by default.

**Comment by calvertdw** [comment]
Here is the "glue" repository for reference.

https://github.com/ihmcrobotics/repository-group

**Comment by dirk-thomas** [comment]
> Here is the "glue" repository for reference.
> https://github.com/ihmcrobotics/repository-group

I am sorry but the example doesn't show me how you get the "set of repositories within". When I fetch the referenced GitHub repository it only contains the 5 files of the repo itself. Please provide a reproducible example how your process works.

**Comment by calvertdw** [comment]
The "git clone <url>" command is run inside that directory. More than once if necessary. Doesn't matter which repository it is. Then you are left with git repositories in that directory.

**Comment by dirk-thomas** [comment]
`vcstool` can only consider repositories which it knows the URL of. In the current examples the URL of e.g. `repository1` is not defined anywhere. I assume the cloning of the sub-repos happens somewhere in your custom build scripts?

Have you tried to specify the nested repositories in a `.repos` file which is used for `vcs import`? The following should work:

```
repositories:
  group:
    type: git
    url: https://github.com/ihmcrobotics/repository-group.git
    version: master
  group/repository1:
    type: git
    url: https://github.com/ihmcrobotics/repository1.git
    version: master
  group/repository2:
    type: git
    url: https://github.com/ihmcrobotics/repository2.git
    version: master
```
